export const mockListings = [
  {
    id: '1',
    url: 'https://www.ebay.com/itm/123456789',
    source: 'ebay',
    title: '2015-2017 Ford F-150 OEM Halogen Headlight - Driver Side',
    description: 'Original equipment manufacturer headlight assembly. Removed from a 2016 F-150 XLT. In excellent condition with no cracks or moisture.',
    price_cents: 12500,
    price_text: '$125.00',
    location: 'Detroit, MI',
    seller_name: 'auto_parts_depot',
    seller_rating: 4.8,
    image_urls: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400'],
  },
  {
    id: '2',
    url: 'https://sfbay.craigslist.org/sfc/pts/d/headlights-toyota-camry-2018/987654321.html',
    source: 'craigslist',
    title: '2018-2020 Toyota Camry LED Headlights (Pair)',
    description: 'Both left and right LED headlights. Upgraded to aftermarket so selling these. Work perfectly, no issues.',
    price_cents: 45000,
    price_text: '$450',
    location: 'San Francisco, CA',
    seller_name: null,
    seller_rating: null,
    image_urls: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400'],
  },
  {
    id: '3',
    url: 'https://www.ebay.com/itm/234567890',
    source: 'ebay',
    title: 'Honda Civic 2016-2018 Right Headlight Assembly OEM',
    description: 'Genuine Honda part. Passenger side headlight in perfect working order. Small scratch on lens.',
    price_cents: 8900,
    price_text: '$89.00',
    location: 'Los Angeles, CA',
    seller_name: 'honda_parts_warehouse',
    seller_rating: 4.9,
    image_urls: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=400'],
  },
  {
    id: '4',
    url: 'https://www.ebay.com/itm/345678901',
    source: 'ebay',
    title: 'Aftermarket LED Headlights for 2014-2018 Chevy Silverado - Black Housing',
    description: 'Brand new aftermarket LED headlights with DRL. Plug and play installation. 1 year warranty included.',
    price_cents: 32999,
    price_text: '$329.99',
    location: 'Houston, TX',
    seller_name: 'ledlights_direct',
    seller_rating: 4.7,
    image_urls: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400'],
  },
  {
    id: '5',
    url: 'https://seattle.craigslist.org/see/pts/d/jeep-wrangler-headlights/876543210.html',
    source: 'craigslist',
    title: 'Jeep Wrangler JK 2007-2018 Headlights - Stock',
    description: 'Stock headlights from my 2015 Wrangler. Upgraded to LED so these need to go. Clean, no damage.',
    price_cents: 6000,
    price_text: '$60',
    location: 'Seattle, WA',
    seller_name: null,
    seller_rating: null,
    image_urls: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400'],
  },
  {
    id: '6',
    url: 'https://www.ebay.com/itm/456789012',
    source: 'ebay',
    title: 'BMW 3 Series F30 2012-2015 Xenon Headlight - Left Side',
    description: 'Authentic BMW xenon headlight. Driver side. Fully functional, includes ballast and bulb.',
    price_cents: 52500,
    price_text: '$525.00',
    location: 'Miami, FL',
    seller_name: 'euro_auto_parts',
    seller_rating: 4.6,
    image_urls: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400'],
  },
  {
    id: '7',
    url: 'https://www.ebay.com/itm/567890123',
    source: 'ebay',
    title: 'Tesla Model 3 2017-2020 Headlight Assembly - Right',
    description: 'OEM Tesla headlight assembly. Passenger side. Removed after minor front end collision repair. Headlight itself undamaged.',
    price_cents: 89000,
    price_text: '$890.00',
    location: 'Palo Alto, CA',
    seller_name: 'tesla_recyclers',
    seller_rating: 4.9,
    image_urls: ['https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400'],
  },
  {
    id: '8',
    url: 'https://phoenix.craigslist.org/cph/pts/d/headlights-nissan-altima/765432109.html',
    source: 'craigslist',
    title: 'Nissan Altima 2019-2021 Headlights Both Sides',
    description: 'Pair of headlights from my 2020 Altima. Totaled in rear-end collision so front end parts are good. Must pick up.',
    price_cents: 25000,
    price_text: '$250',
    location: 'Phoenix, AZ',
    seller_name: null,
    seller_rating: null,
    image_urls: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400'],
  },
]
